---
# This is an example configuration file for the AdWords API client library.
# Please fill in the required fields, and copy it over to your home directory.
:authentication:
  # Authentication method, for web applications OAuth is recommended.
  :method: OAuth

  # Auth parameters for OAuth method.
  # Set the OAuth consumer key and secret. Anonymous values can be used for
  # testing, and real values can be obtained by registering your application:
  # http://code.google.com/apis/accounts/docs/RegistrationForWebAppsAuto.html
  :oauth_consumer_key: anonymous
  :oauth_consumer_secret: anonymous
  # If you manage or store access token manually, you can specify it here.
  #:oauth_token: INSERT_OAUTH_TOKEN_HERE
  # If you need to change signature method, specify it here.
  #:oauth_signature_method: HMAC-SHA1
  # Token secret for HMAC-SHA1 method.
  #:oauth_token_secret: INSERT_OAUTH_TOKEN_SECRET_HERE

  # Other parameters.
  :developer_token: INSERT_YOUR_DEVELOPER_TOKEN_HERE
  # If you access only one account you can specify it here.
  # :client_customer_id: INSERT_YOUR_CLIENT_CUSTOMER_ID_HERE
  :user_agent: demo-rails
:service:
  # Environment to access: SANDBOX or PRODUCTION.
  :environment: PRODUCTION
:connection:
  # Enable to request all responses to be compressed.
  :enable_gzip: false
  # If your proxy connection requires authentication, make sure to include it in
  # the URL, e.g.: http://user:password@proxy_hostname:8080
  # :proxy: INSERT_PROXY_HERE
:library:
  :log_level: INFO
